name: Go

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:

  Lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26

  Test-Ubuntu:
    name: Test-Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: make test-coverage
        env:
          MQTT_TEST_SERVER: ${{ secrets.MQTT_TEST_SERVER }}

  Test-MacOS:
    name: Test-MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: make test-coverage
        env:
          MQTT_TEST_SERVER: ${{ secrets.MQTT_TEST_SERVER }}

  Test-windows:
    name: Test-MacOS
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: make test-coverage
        env:
          MQTT_TEST_SERVER: ${{ secrets.MQTT_TEST_SERVER }}
